from time import sleep

from Facebook.BaseTest.registrationLocator import *
from selenium import webdriver
from selenium.webdriver.common.by import By
import pytest


def test_registration():
    driver = webdriver.Chrome()
    driver.get(registrationLink1 )
    driver.maximize_window()
    driver.find_element(By.XPATH, registrationLink2).click()
    sleep(12)
    firstName = driver.find_element(By.XPATH, registrationLink3)
    sleep(12)
    firstName.click()
    firstName.send_keys("aman")
    sleep(12)
    lastName = driver.find_element(By.XPATH, registrationLink4)
    sleep(12)
    lastName.click()
    lastName.send_keys("aluza")
    sleep(12)
    email = driver.find_element(By.XPATH,registrationLink5)
    sleep(12)
    email.click()
    email.send_keys("fentahunadisu16@gmail.com")
    sleep(12)
    Re_email = driver.find_element(By.XPATH,registrationLink51)
    sleep(12)
    Re_email.click()
    Re_email.send_keys("fentahunadisu16@gmail.com")
    sleep(12)
    password = driver.find_element(By.XPATH, registrationLink6)
    sleep(12)
    password.click()
    password.send_keys("fentish1234")
    sleep(12)
    driver.find_element(By.XPATH, registrationLink7).click()
    sleep(12)
    year_correct = driver.find_element(By.XPATH, registrationLink8)
    sleep(12)
    year_correct.send_keys("1990")
    driver.find_element(By.XPATH, registrationLink9).click()
    sleep(3)
    driver.find_element(By.XPATH, registrationLink10).click()
    sleep(100)


def test_registration_without_email():
    driver = webdriver.Chrome()
    driver.get(registrationLink1 )
    driver.maximize_window()
    driver.find_element(By.XPATH, registrationLink2).click()
    sleep(12)
    firstName = driver.find_element(By.XPATH, registrationLink3)
    sleep(12)
    firstName.click()
    firstName.send_keys("aman")
    sleep(12)
    lastName = driver.find_element(By.XPATH, registrationLink4)
    sleep(12)
    lastName.click()
    lastName.send_keys("aluza")
    sleep(12)
    email = driver.find_element(By.XPATH,registrationLink5)
    sleep(12)
    email.click()
    email.send_keys("")
    sleep(12)
    Re_email = driver.find_element(By.XPATH,registrationLink51)
    sleep(12)
    Re_email.click()
    Re_email.send_keys("fentahunadisu16@gmail.com")
    sleep(12)
    password = driver.find_element(By.XPATH, registrationLink6)
    sleep(12)
    password.click()
    password.send_keys("fentish1234")
    sleep(12)
    driver.find_element(By.XPATH, registrationLink7).click()
    sleep(12)
    year_correct = driver.find_element(By.XPATH, registrationLink8)
    sleep(12)
    year_correct.send_keys("1990")
    driver.find_element(By.XPATH, registrationLink9).click()
    sleep(3)
    driver.find_element(By.XPATH, registrationLink10).click()
    sleep(100)


def test_registration_without_password():
    driver = webdriver.Chrome()
    driver.get(registrationLink1 )
    driver.maximize_window()
    driver.find_element(By.XPATH, registrationLink2).click()
    sleep(12)
    firstName = driver.find_element(By.XPATH, registrationLink3)
    sleep(12)
    firstName.click()
    firstName.send_keys("aman")
    sleep(12)
    lastName = driver.find_element(By.XPATH, registrationLink4)
    sleep(12)
    lastName.click()
    lastName.send_keys("aluza")
    sleep(12)
    email = driver.find_element(By.XPATH,registrationLink5)
    sleep(12)
    email.click()
    email.send_keys("fentahunadisu16@gmail.com")
    sleep(12)
    Re_email = driver.find_element(By.XPATH,registrationLink51)
    sleep(12)
    Re_email.click()
    Re_email.send_keys("fentahunadisu16@gmail.com")
    sleep(12)
    password = driver.find_element(By.XPATH, registrationLink6)
    sleep(12)
    password.click()
    password.send_keys("")
    sleep(12)
    driver.find_element(By.XPATH, registrationLink7).click()
    sleep(12)
    year_correct = driver.find_element(By.XPATH, registrationLink8)
    sleep(12)
    year_correct.send_keys("1990")
    driver.find_element(By.XPATH, registrationLink9).click()
    sleep(3)
    driver.find_element(By.XPATH, registrationLink10).click()
    sleep(100)


def test_registration_without_email_and_password():
    driver = webdriver.Chrome()
    driver.get(registrationLink1 )
    driver.maximize_window()
    driver.find_element(By.XPATH, registrationLink2).click()
    sleep(12)
    firstName = driver.find_element(By.XPATH, registrationLink3)
    sleep(12)
    firstName.click()
    firstName.send_keys("aman")
    sleep(12)
    lastName = driver.find_element(By.XPATH, registrationLink4)
    sleep(12)
    lastName.click()
    lastName.send_keys("aluza")
    sleep(12)
    email = driver.find_element(By.XPATH,registrationLink5)
    sleep(12)
    email.click()
    email.send_keys("")
    sleep(12)
    Re_email = driver.find_element(By.XPATH,registrationLink51)
    sleep(12)
    Re_email.click()
    Re_email.send_keys("")
    sleep(12)
    password = driver.find_element(By.XPATH, registrationLink6)
    sleep(12)
    password.click()
    password.send_keys("")
    sleep(12)
    driver.find_element(By.XPATH, registrationLink7).click()
    sleep(12)
    year_correct = driver.find_element(By.XPATH, registrationLink8)
    sleep(12)
    year_correct.send_keys("1990")
    driver.find_element(By.XPATH, registrationLink9).click()
    sleep(3)
    driver.find_element(By.XPATH, registrationLink10).click()
    sleep(100)
